### ISSUE TITLE
Log determinant has wrong dimensions?

### ISSUE THREAD

**Issue by matejgrcic** [rosinality/glow-pytorch#14]
**Issue**
I've printed `log_p` and `logdet` returned by the model. It seems that `log_p_sum` has the size equal to the batch size (which is fine) but the `logdet` contains a single value. Should `logdet` have the same dimensions as `log_p`?

**Code for reproducing**
Add the following code to train.py line 120.
`
print(log_p.size(), logdet.size())
`

**Comment by rosinality** [comment]
If you use additive coupling and not affine coupling, logdet will not have batch dimensions.
