### ISSUE TITLE
 (why use torch_rand_noise as input?) input 에서의 torch_rand_noise 의 이유

### ISSUE THREAD

**Issue by Meric3** [rosinality/glow-pytorch#18]
안녕하세요. 좋은 코드 감사합니다. 

사용 중 질문이 생겨서 이슈에 남깁니다. 

어째서 input에 torch_rand 를 넣어서 사용하시는 건가요? 

제가 레퍼런스나 다른 구현된 코드 등을 보았을 때는 이에 대한 설명이 없어서 문의 드립니다.

감사합니다.  

(한글이나 영어답변 무엇이든 괜찮습니다. 제가 영어가 부족해서 제목에 핵심 문장만 넣었습니다.)

**Comment by rosinality** [comment]
이미지 데이터는 양자화된 이산적 데이터이기 때문에 노이즈를 추가해서 continuous한 값을 갖도록 만들어줍니다. 이 논문을 참고하세요: https://arxiv.org/abs/1511.01844

**Comment by Meric3** [comment]
감사합니다!
rosinality comment : 
Since image data is dicrete data, he add noise. then the data become continuous. reference : https://arxiv.org/abs/1511.01844
