### ISSUE TITLE
Weight and bias intialization for AffineCoupling

### ISSUE THREAD

**Issue by saandeepa93** [rosinality/glow-pytorch#22]
Hello! Great work on following the implementation of the paper in the code. Makes the paper very lucid.
I have a couple of questions on the AffineCoupling class under the model.py file.

1. Is there any reason you initialized the weight and bias of the last ZeroConv2d layer with zeros?
2. What is the idea behind using some scale value and mulitplying the output of convolution with the exp(scale) in ZeroConv2d?

**Comment by rosinality** [comment]
Actually I don't know the exact reason why the author used it. I think it is because it could make the network at initializations AffineCoupling behave like identity. And maybe using exp(3 * scale) makes learn to global scaling in AffineCoupling more easier. But again I'm not sure why.
