### ISSUE TITLE
Why are we sampling z from the standard normal distribution instead of the learned p(z)?

### ISSUE THREAD

**Issue by icbcbicc** [rosinality/glow-pytorch#23]
Hi rosinality,

Your code is clean and easy to read. Thank you for your effort. 

I have one question: During the sampling process, why are we sampling z from the standard normal distribution (with temperature)? Shouldn't we sample from the learned p(z)? Is it because p(z) is dependant on the data so that we cannot sample from it? (In the implementation, if I'm understanding it correctly, p(z) has four components, three of them are dependent on both the data and the model, while the last one is only dependant on the model.)

Thanks.

**Comment by rosinality** [comment]
Learned priors used in the sampling step. Please refer to this: https://github.com/rosinality/glow-pytorch/blob/97081ff115a694cf04aeedbd58447f33d242c879/model.py#L309

**Comment by icbcbicc** [comment]
Thanks for your reply!
