### ISSUE TITLE
Conditional Gaussian prior parameters produce unnormalized likelihoods

### ISSUE THREAD

**Issue by braun-steven** [rosinality/glow-pytorch#29]
Hi,

first off, thank you for you implementation! 

I found, that you've deviated from the original OpenAI implementation and enabled to produce the prior parameters (mean, logsd) from the intermediate flow splits via an additional convolution https://github.com/rosinality/glow-pytorch/blob/97081ff115a694cf04aeedbd58447f33d242c879/model.py#L285

Unfortunately, this little change leads to the Gauss distribution being unnormalized. If you think about it: let's say the convolution that produces the prior parameters (mean, logsd) will learn to produce `mean = z_new, logsd = 0`. Then the gaussian prior likelihood for `z_new`: `N(z_new; mean=z_new, sd=1)` will always have maximum likelihood, since the query values `z_new` are equal to the distribution mode. So, if you integrate this term for all `z_new in R` (lets keep it simple one-dimensional), you will end up with a value > 1 (should be infinity), showing that this way of defining the prior leads to an unnormalized distribution.

To fix this you need to (as done in the original OpenAI implementation) remove the condition of the mean and logsd on the split variables and just learn them from a fixed input. Relevant pieces of the original implementation:

Prior is created unconditionally
https://github.com/openai/glow/blob/master/model.py#L180

Fixed zero input
https://github.com/openai/glow/blob/master/model.py#L109

If parameters are learned, apply convolution on fixed input
https://github.com/openai/glow/blob/master/model.py#L111

Create prior from mean and logsd 
https://github.com/openai/glow/blob/master/model.py#L116

**Comment by rosinality** [comment]
I think https://github.com/rosinality/glow-pytorch/blob/master/model.py#L285 corresponds to https://github.com/openai/glow/blob/master/model.py#L89, which is conditioned on latents, and https://github.com/openai/glow/blob/master/model.py#L180 corresponds to https://github.com/rosinality/glow-pytorch/blob/master/model.py#L346.

**Comment by braun-steven** [comment]
Thanks for your swift reply :) 

You're absolutely right! I missed that part. Well, then your implementation is correct and I still don't understand how this represents a prior. I need to do some math to see if I can show/provide a counter-example.

It's unfortunate that this isn't even mentioned in the Glow paper (the fact that the prior params are conditioned on the latents). I'll close this issue as this has nothing to do with your specific implementation anymore, thanks :)
