### ISSUE TITLE
Act Norm Output issue 

### ISSUE THREAD

**Issue by kelvinaaa2** [rosinality/glow-pytorch#39]
![image](https://user-images.githubusercontent.com/68983001/157929828-cc089e40-aa29-4d54-b881-4df59e5c30db.png)

the actnorm function is 

===
s * input + b
===

But saw the implementation,
```
 if self.logdet:
         return self.scale * (input + self.loc), logdet
```
which means that it has become 

===
s * (input + b)
===

Is it doing on purpose? Or did I get something wrong with the paper?

**Comment by rosinality** [comment]
It follows the official implementation, and it is different from the detail specified in the paper.
